# Generated by Django 4.2.1 on 2023-06-15 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_vocabulary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartOfSpeech',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_type', models.CharField(choices=[('verb', 'Verb'), ('noun', 'Noun'), ('adjective', 'Adjective'), ('phrasal_verb', 'Phrasal Verb')], max_length=20)),
                ('definition', models.CharField(max_length=300)),
                ('example', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('word_types', models.ManyToManyField(blank=True, related_name='word_types', to='manage_vocabulary.partofspeech')),
            ],
        ),
    ]
