# Generated by Django 4.2.1 on 2023-06-15 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_vocabulary', '0002_partofspeech_word'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('definition', models.CharField(max_length=300)),
                ('example', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='partofspeech',
            name='definition',
        ),
        migrations.RemoveField(
            model_name='partofspeech',
            name='example',
        ),
        migrations.AddField(
            model_name='partofspeech',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='groups', to='manage_vocabulary.group'),
        ),
    ]
