# Generated by Django 4.2.1 on 2023-06-17 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage_vocabulary', '0002_word_wordentry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='word',
            name='updated_date',
        ),
    ]
