# Generated by Django 4.2.1 on 2023-06-16 01:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('manage_vocabulary', '0002_word_wordentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='word',
            name='updated_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
