# Generated by Django 4.2.1 on 2023-06-19 02:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manage_vocabulary', '0002_word_wordentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordentry',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='word_entries', to=settings.AUTH_USER_MODEL),
        ),
    ]
