# Generated by Django 4.2.1 on 2023-06-16 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_vocabulary', '0003_word_created_date_word_updated_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordentry',
            name='word_type',
            field=models.CharField(choices=[('verb', 'Verb'), ('noun', 'Noun'), ('adjective', 'Adjective'), ('phrasal_verb', 'Phrasal Verb'), ('adverb', 'Adverb')], max_length=20),
        ),
    ]
