# Generated by Django 4.2.2 on 2023-06-22 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_vocabulary', '0003_alter_wordentry_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('your_name', models.CharField(max_length=100)),
                ('your_email', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
            ],
        ),
    ]
