# Generated by Django 4.2.1 on 2023-06-17 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage_vocabulary', '0003_remove_word_created_date_remove_word_updated_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='word',
            old_name='owner',
            new_name='owners',
        ),
    ]
