# Generated by Django 4.2.5 on 2023-09-25 20:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('manage_vocabulary', '0004_alter_word_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='owners',
        ),
        migrations.CreateModel(
            name='WordOwnership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manage_vocabulary.word')),
            ],
            options={
                'unique_together': {('user', 'word')},
            },
        ),
    ]
