# Generated by Django 4.2.1 on 2023-06-17 03:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_vocabulary', '0004_rename_owner_word_owners'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='owners',
        ),
        migrations.AddField(
            model_name='word',
            name='owners',
            field=models.ManyToManyField(blank=True, related_name='words', to=settings.AUTH_USER_MODEL),
        ),
    ]
