# Generated by Django 4.2.5 on 2023-09-25 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage_vocabulary', '0005_remove_word_owners_wordownership'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='added_date',
        ),
    ]
