# Generated by Django 4.2.5 on 2023-09-26 00:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manage_vocabulary', '0006_remove_word_added_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordentry',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='words_ownership', to='manage_vocabulary.wordownership'),
        ),
    ]
