# Generated by Django 4.2.5 on 2023-09-26 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage_vocabulary', '0007_wordentry_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wordentry',
            name='user',
        ),
        migrations.RemoveField(
            model_name='wordentry',
            name='word',
        ),
    ]
