# Generated by Django 4.2.5 on 2023-09-26 00:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manage_vocabulary', '0008_remove_wordentry_user_remove_wordentry_word'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordentry',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='words_ownership', to='manage_vocabulary.wordownership'),
        ),
    ]
