# Generated by Django 4.2.5 on 2023-09-26 01:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manage_vocabulary', '0009_alter_wordentry_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wordentry',
            name='owner',
        ),
        migrations.AddField(
            model_name='wordentry',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='word_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='wordentry',
            name='word',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='word_entries', to='manage_vocabulary.word'),
        ),
    ]
