# Generated by Django 4.2.5 on 2023-09-26 01:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manage_vocabulary', '0010_remove_wordentry_owner_wordentry_user_wordentry_word'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordentry',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='word_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='wordentry',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='word_entries', to='manage_vocabulary.word'),
        ),
    ]
